# This is a basic workflow to help you get started with Actions

name: Build and Push

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - uses: actions/checkout@v2
#       - name: Build image
#         run: docker build -t $LOGIN/$NAME:latest ./project
#       - name: Docker login
#         run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
#       - name: Push image
#         run: docker push $LOGIN/$NAME:latest
      - name: Publish
        run: |
          sudo apt-get install sshpass
          sshpass -p ${{ secrets.VIRTUAL_PASS }} ssh ${{ secrets.VIRTUAL_LOGIN }}@${{ secrets.VIRTUAL_IP }} -tt
          mkdir forCiCd
        
