# This is a basic workflow to help you get started with Actions

name: Build and Push

on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest ./project
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Push image
        run: docker push $LOGIN/$NAME:latest
  job2:
    name: Publish
    needs: job1
    runs-on: ubuntu-latest
    steps:
        - name: Run sshpass commands
          uses: matheusvanzan/sshpass-action@v2
          with:
            host: ${{ secrets.VIRTUAL_IP }}
            user: ${{ secrets.VIRTUAL_LOGIN }}
            pass: ${{ secrets.VIRTUAL_PASS }}
            run: |
              cd forCiCD
              docker-compose pull
              docker-compose up -d
        - name: Send mail
          if: always()
          uses: dawidd6/action-send-mail@v2
          with:
            # mail server settings
            server_address: smtp.gmail.com
            server_port: 465
            # user credentials
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            # email subject
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            # email body as text
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            # comma-separated string, send email to
            to: sashalev200149@gmail.com, school200149@gmail.com
            # from email name
            from: Alex Lev
